### ISSUE TITLE
Manual Testing of Extension

### ISSUE THREAD

**Issue by lalit10** [lalit10/SimplyClip#23]

**Comment by apande95** [comment]
Verified Functionality.
<img width="440" alt="Screen Shot 2021-09-30 at 1 37 45 PM" src="https://user-images.githubusercontent.com/11155124/135563095-d895c48c-c69a-4a48-a990-76b09cd988e2.png">

**Comment by apande95** [comment]
After Copy
<img width="440" alt="Screen Shot 2021-09-30 at 11 57 57 PM" src="https://user-images.githubusercontent.com/11155124/135563152-80f2adab-fdc5-41af-ae59-f8c89b289d66.png">
